import { MenuItem } from "@shared/models/menuItems";

export const menuItems: MenuItem[] = [

  {
    title: 'Roles',
    icon: 'team',
    route: 'roles',
    theme: 'outline',
    state: false,
    Role: 'Usuario',
  },
  {
    title: 'Centro Formativo',
    icon: 'bank',
    route: 'training-centers',
    theme: 'outline',
    state: false,
    Role: 'Usuario',
  },
  {
    title: 'Areas',
    icon: 'appstore',
    route: 'environments-area',
    theme: 'outline',
    state: false,
    Role: 'Usuario',
  },
  {
    title: 'Programas',
    icon: 'project',
    route: 'programs',
    theme: 'outline',
    state: false,
    Role: 'Usuario',
  },
  {
    title:'Sedes',
    route:'headquarters',
    icon:'home',
    theme:'outline',
    state:false,
    Role:'Usuario'
  },
  {
    title: 'Ambientes',
    icon: 'environment',
    route: 'environments',
    theme: 'outline',
    state: false,
    Role: 'Usuario',
  },
  {
    title: 'Fichas',
    icon: 'read',
    route: 'file',
    theme: 'outline',
    state: false,
    Role: 'Usuario',
  },
  {
    title: 'Sesiones',
    icon: 'profile',
    route: 'session',
    theme: 'outline',
    state: false,
    Role: 'Usuario',
  },
  {
    title: 'Gestion',
    icon: 'profile',
    route: 'managesession',
    theme: 'outline',
    state: false,
    Role: 'Usuario',
  },
  {
    title: 'Calendario',
    icon: 'calendar',
    route: 'session-calendar',
    theme: 'outline',
    state: false,
    Role: 'Usuario',
  },
  {
    title: 'Asistencia',
    icon: 'check-square',
    route: 'fichas/:course_code/attendance',
    theme: 'outline',
    state: false,
    Role: 'Usuario',
  },
  {
    title: 'Inasistencias',
    icon: 'user',
    route: 'absences',
    theme: 'outline',
    state: false,
    Role: 'Usuario',
  },
  {
    title: 'Justificaciones',
    icon: 'file-text',
    route: 'justification',
    theme: 'outline',
    state: false,
    Role: 'Usuario',
  }
];
